#!/usr/bin/env python
"""
Compare lineouts from CalibrantPanelShiftsOMP (.lineout.xy) and
extract_lineouts (_lineout.xy) with ideal calibrant ring positions.

Usage:
    python plot_lineout_comparison.py calibrant.lineout.xy [integrator_lineout.xy]
        --paramFN parameters.txt

If only the calibrant lineout is specified, it is plotted alone.
If the integrator lineout is also given, both are overlaid.
Ideal 2theta lines are drawn from hkls.csv (generated by GetHKLList).
"""

import argparse
import math
import sys
from pathlib import Path
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import numpy as np


def read_geometry(param_file):
    """Read geometry parameters needed for R → 2θ conversion."""
    geom = {'px': 172.0, 'Lsd': 0.0, 'Wavelength': 0.0,
             'RMin': 10.0, 'RMax': 1200.0, 'RBinSize': 0.25}
    with open(param_file) as f:
        for line in f:
            parts = line.strip().split()
            if not parts:
                continue
            key = parts[0]
            if key in geom and len(parts) >= 2:
                geom[key] = float(parts[1])
    return geom

def read_lineout_xy(path, geom=None):
    """Read a .lineout.xy, _lineout.xy text file, OR _lineout.bin binary.

    For .bin files, `geom` must provide px, Lsd, RMin, RBinSize for R→2θ.
    Returns (tth, intensity) as numpy arrays.
    """
    p = Path(path)
    if p.suffix == '.bin':
        # Binary: array of doubles, one per R bin
        if geom is None:
            raise ValueError(f"{path} is .bin but no --paramFN given for R→2θ")
        data = p.read_bytes()
        n = len(data) // 8
        import struct
        intensities = np.array(struct.unpack(f'{n}d', data[:n*8]))
        px = geom['px']
        Lsd = geom['Lsd']
        RMin = geom['RMin']
        RBinSize = geom['RBinSize']
        tth = np.degrees(np.arctan(
            (RMin + (np.arange(n) + 0.5) * RBinSize) * px / Lsd))
        # Filter out NaN (contaminated by masked pixels)
        valid = ~np.isnan(intensities)
        return tth[valid], intensities[valid]

    # Text: two-column (.xy)
    tth, intensity = [], []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) >= 2:
                tth.append(float(parts[0]))
                intensity.append(float(parts[1]))
    return np.array(tth), np.array(intensity)


def read_ideal_2thetas(param_fn):
    """Read ideal 2theta values from hkls.csv (in same dir as paramFN)
    and from the parameter file's lattice + wavelength.

    Returns list of (ringNr, 2theta_deg) tuples.
    """
    param_path = Path(param_fn).resolve()
    param_dir = param_path.parent

    # Parse Wavelength, Lsd, MaxRingRad from parameter file
    wavelength = None
    lsd = None
    max_ring_rad = None
    folder = param_dir
    for line in open(param_path):
        parts = line.strip().split()
        if not parts:
            continue
        if parts[0] == 'Wavelength' and len(parts) >= 2:
            wavelength = float(parts[1])
        elif parts[0] == 'Lsd' and len(parts) >= 2:
            lsd = float(parts[1])
        elif parts[0] == 'MaxRingRad' and len(parts) >= 2:
            max_ring_rad = float(parts[1])
        elif parts[0] == 'Folder' and len(parts) >= 2:
            folder = Path(parts[1])

    # Try to find hkls.csv
    hkls_path = folder / 'hkls.csv'
    if not hkls_path.exists():
        hkls_path = param_dir / 'hkls.csv'
    if not hkls_path.exists():
        print(f"  Warning: hkls.csv not found in {folder} or {param_dir}")
        return []

    max_tth = 180.0
    if max_ring_rad and lsd:
        max_tth = math.degrees(math.atan(max_ring_rad / lsd))

    rings = []
    seen_rings = set()
    with open(hkls_path) as f:
        f.readline()  # skip header
        for line in f:
            parts = line.strip().split()
            if len(parts) < 9:
                continue
            ring_nr = int(parts[4])
            theta = float(parts[8])          # Bragg angle
            tth = 2 * theta                  # 2theta in degrees
            if tth > max_tth:
                break
            if ring_nr not in seen_rings:
                rings.append((ring_nr, tth))
                seen_rings.add(ring_nr)

    return rings


def main():
    parser = argparse.ArgumentParser(
        description='Compare CalibrantPanelShiftsOMP and IntegratorZarrOMP lineouts')
    parser.add_argument('calibrant_lineout',
                        help='CalibrantPanelShiftsOMP .lineout.xy file')
    parser.add_argument('integrator_lineout', nargs='?', default=None,
                        help='IntegratorZarrOMP _lineout.xy file (optional)')
    parser.add_argument('--paramFN', required=True,
                        help='Parameter file (for ideal ring positions)')
    parser.add_argument('--xlim', type=float, nargs=2, default=None,
                        help='2theta range to plot, e.g. --xlim 0.5 5.0')
    parser.add_argument('--log', action='store_true',
                        help='Use log scale for intensity')
    args = parser.parse_args()

    # Read geometry (needed for .bin → 2θ conversion)
    geom = read_geometry(args.paramFN)

    # Read calibrant lineout
    calib_path = Path(args.calibrant_lineout)
    if not calib_path.exists():
        print(f"Error: {calib_path} not found")
        sys.exit(1)
    calib_tth, calib_int = read_lineout_xy(calib_path, geom)
    print(f"Calibrant lineout: {len(calib_tth)} points, "
          f"2θ=[{calib_tth[0]:.3f}, {calib_tth[-1]:.3f}] deg")

    # Read integrator lineout if provided
    integ_tth, integ_int = None, None
    if args.integrator_lineout:
        integ_path = Path(args.integrator_lineout)
        if not integ_path.exists():
            print(f"Error: {integ_path} not found")
            sys.exit(1)
        integ_tth, integ_int = read_lineout_xy(integ_path, geom)
        print(f"Integrator lineout: {len(integ_tth)} points, "
              f"2θ=[{integ_tth[0]:.3f}, {integ_tth[-1]:.3f}] deg")

    # Read ideal ring positions
    rings = read_ideal_2thetas(args.paramFN)
    print(f"Ideal rings: {len(rings)} rings loaded")

    # Plot
    fig, ax = plt.subplots(figsize=(14, 6))

    ax.plot(calib_tth, calib_int, '-', linewidth=0.8, alpha=0.9,
            color='#2196F3', label=f'Calibrant ({calib_path.name})')

    if integ_tth is not None:
        ax.plot(integ_tth, integ_int, '-', linewidth=0.8, alpha=0.9,
                color='#FF5722', label=f'Integrator ({integ_path.name})')

    # Draw ideal 2theta lines
    ymin, ymax = ax.get_ylim()
    for i, (ring_nr, tth) in enumerate(rings):
        label = 'Ideal 2θ (hkls)' if i == 0 else None
        ax.axvline(tth, color='#4CAF50', linewidth=0.5, alpha=0.6,
                   linestyle='--', label=label)
        # Label first few rings
        if i < 20:
            ax.text(tth, ymax * 0.95, f'{ring_nr}', fontsize=6,
                    ha='center', va='top', color='#4CAF50', alpha=0.8,
                    rotation=90)

    ax.set_xlabel('2θ (degrees)', fontsize=12)
    ax.set_ylabel('Intensity (area-weighted avg)', fontsize=12)
    ax.set_title('Lineout Comparison: CalibrantPanelShiftsOMP vs IntegratorZarrOMP',
                 fontsize=13)
    ax.legend(fontsize=10, loc='upper right')
    ax.grid(True, alpha=0.3)

    if args.xlim:
        ax.set_xlim(args.xlim)
    if args.log:
        ax.set_yscale('log')

    plt.tight_layout()
    plt.show()


# MIDAS version banner
try:
    import sys as _sys, os as _os
    _sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))), 'utils'))
    from version import version_string as _vs
    print(_vs())
except Exception:
    pass

if __name__ == '__main__':
    main()
