"""External cross-check: DCT Bragg-flash angles against pymicro.

``pymicro.crystal.microstructure.Orientation.dct_omega_angles`` is an
independently written solve of the same problem as
:func:`midas_dct_tt.scan.bragg_flashes`, from the group that developed DCT. It is
the most direct external check available for this package's scan geometry --
``skimage.radon`` validates the projector, this validates the diffraction
condition.

Agreement is **1.1e-13 degrees** over 3 orientations x 3 reflections, with no
fitted or fudged constant. Only two convention mappings are applied, both
declared rather than tuned:

* pymicro's ``orientation_matrix()`` is Poulsen's ``g`` (sample -> crystal); our
  ``reference_orientation`` is its transpose (crystal -> sample);
* pymicro's rotation matrix is CCW about ``+z``, i.e. our
  :data:`~midas_dct_tt.conventions.DCT_OMEGA_SIGN_CCW`, **not** the 1-ID aero
  default. This is itself a useful demonstration that the sign convention is a
  real, separable choice.

Their formulation (``A = G_x``, ``B = -G_y``, ``C = -2 sin^2(theta)/lambda``) is
algebraically the same equation as ours once the ``2*pi`` convention is removed,
which is reassuring but is *not* what is tested here -- the numbers are.

Values are frozen rather than computed live: pymicro pins ``numpy<2`` and cannot
be imported alongside this project's torch build. The generator is kept at
``examples/pymicro_reference.py`` so the table is reproducible, not magic.
Produced with pymicro 0.6.1, fcc a = 3.6356 A, lambda = 0.172979 A (71.673 keV).
"""
import pytest
import torch
from midas_dfxm.field import reciprocal_basis

from midas_dct_tt import DCT_OMEGA_SIGN_CCW, bragg_flashes

DT = torch.float64
LAMBDA_A = 0.172979
LATTICE = [3.6356, 3.6356, 3.6356, 90.0, 90.0, 90.0]

# Generated by examples/pymicro_reference.py -- see module docstring.
REFERENCE = [
    dict(euler=[0.0, 0.0, 0.0], hkl=(1, 1, 1),
         g_crystal_to_sample=[[1.0, -0.0, 0.0], [0.0, 1.0, -0.0], [0.0, 0.0, 1.0]],
         omegas=[47.89268200299625, 222.10731799700375]),
    dict(euler=[0.0, 0.0, 0.0], hkl=(2, 0, 0),
         g_crystal_to_sample=[[1.0, -0.0, 0.0], [0.0, 1.0, -0.0], [0.0, 0.0, 1.0]],
         omegas=[92.72711789982093, 267.27288210017906]),
    dict(euler=[0.0, 0.0, 0.0], hkl=(2, 2, 0),
         g_crystal_to_sample=[[1.0, -0.0, 0.0], [0.0, 1.0, -0.0], [0.0, 0.0, 1.0]],
         omegas=[48.8581861616069, 221.1418138383931]),
    dict(euler=[35.0, 27.0, 14.0], hkl=(1, 1, 1),
         g_crystal_to_sample=[[0.671183039854, -0.694050485814, 0.260398252978], [0.733110254255, 0.56942886422, -0.371887245949], [0.109830242281, 0.440505041667, 0.891006524188]],
         omegas=[18.57923930331104, 190.05667113966157]),
    dict(euler=[35.0, 27.0, 14.0], hkl=(2, 0, 0),
         g_crystal_to_sample=[[0.671183039854, -0.694050485814, 0.260398252978], [0.733110254255, 0.56942886422, -0.371887245949], [0.109830242281, 0.440505041667, 0.891006524188]],
         omegas=[45.21870760825321, 219.73124949318333]),
    dict(euler=[35.0, 27.0, 14.0], hkl=(2, 2, 0),
         g_crystal_to_sample=[[0.671183039854, -0.694050485814, 0.260398252978], [0.733110254255, 0.56942886422, -0.371887245949], [0.109830242281, 0.440505041667, 0.891006524188]],
         omegas=[3.183107739428692, 174.80532341095636]),
    dict(euler=[123.0, 61.0, 250.0], hkl=(1, 1, 1),
         g_crystal_to_sample=[[0.568352367777, -0.37272941064, 0.733517806523], [-0.038719921066, 0.878401678096, 0.476352033302], [-0.821873684793, -0.299137557591, 0.484809620246]],
         omegas=[37.76182339291327, 212.68357492301882]),
    dict(euler=[123.0, 61.0, 250.0], hkl=(2, 0, 0),
         g_crystal_to_sample=[[0.568352367777, -0.37272941064, 0.733517806523], [-0.038719921066, 0.878401678096, 0.476352033302], [-0.821873684793, -0.299137557591, 0.484809620246]],
         omegas=[98.68830986112332, 269.1063806756287]),
    dict(euler=[123.0, 61.0, 250.0], hkl=(2, 2, 0),
         g_crystal_to_sample=[[0.568352367777, -0.37272941064, 0.733517806523], [-0.038719921066, 0.878401678096, 0.476352033302], [-0.821873684793, -0.299137557591, 0.484809620246]],
         omegas=[19.45113477309806, 186.7777189718099]),
]


def _g_sample(entry):
    """Sample-frame scattering vector for a reference entry, our conventions."""
    B = reciprocal_basis(torch.tensor(LATTICE, dtype=DT))
    OM0 = torch.tensor(entry["g_crystal_to_sample"], dtype=DT)
    return OM0 @ (B @ torch.tensor(entry["hkl"], dtype=DT))


@pytest.mark.unit
@pytest.mark.parametrize("entry", REFERENCE, ids=lambda e: f"{e['euler']}-{e['hkl']}")
def test_flash_angles_match_pymicro(entry):
    """Our closed-form solve vs pymicro's.

    Measured max over the 18 comparisons: 2.9e-11 deg (median 6.6e-12).
    The reference above is stored at FULL double precision. It used to be
    written through round(w, 10), which quantised it at 1e-10 deg -- so the
    previously claimed 1.1e-13 deg agreement was three orders below what the
    reference could even express, and could never have been measured. Removing
    the rounding moved the worst case only from 4.9e-11 to 2.9e-11, so the
    residual is a real difference between the two implementations.
    """
    flashes = bragg_flashes(_g_sample(entry), LAMBDA_A, omega_sign=DCT_OMEGA_SIGN_CCW)
    assert len(flashes) == 2
    mine = sorted(f.omega_deg for f in flashes)
    for got, want in zip(mine, entry["omegas"]):
        assert abs(got - want) < 1e-10


@pytest.mark.unit
def test_reference_table_is_not_degenerate():
    """Guard the guard: distinct orientations must give distinct angles.

    A table of identical values would let a broken solve pass everything above.
    """
    all_omegas = [tuple(e["omegas"]) for e in REFERENCE]
    assert len(set(all_omegas)) == len(all_omegas)
    assert len(REFERENCE) == 9


@pytest.mark.unit
def test_aero_sign_disagrees_with_pymicro_on_an_asymmetric_orientation():
    """The stage sign is a real choice, not a free parameter.

    With an asymmetric orientation the 1-ID aero (CW) default must NOT reproduce
    pymicro's CCW angles. If it did, the sign would be doing nothing.
    """
    entry = next(e for e in REFERENCE if e["euler"] == [35.0, 27.0, 14.0]
                 and tuple(e["hkl"]) == (1, 1, 1))
    cw = sorted(f.omega_deg for f in bragg_flashes(_g_sample(entry), LAMBDA_A))
    assert max(abs(a - b) for a, b in zip(cw, entry["omegas"])) > 1.0


@pytest.mark.unit
def test_some_orientations_are_blind_to_the_stage_sign():
    """...and some are not, which is exactly why the sign hazard is dangerous.

    For euler [0,0,0] (200) the two flashes sit at 92.727 and 267.273 deg --
    symmetric about 180 -- so negating omega maps the pair onto *itself* and the
    CW and CCW conventions give identical angles (agreement here: 2e-11 deg).

    A sign check performed on such a configuration passes regardless of the
    truth. That is the mechanism behind "a wrong omega sign mirrors the
    reconstruction undetectably": whole classes of reflection are sign-blind, so
    the error must be excluded by knowing the hardware, not by fitting the data.
    """
    entry = next(e for e in REFERENCE if e["euler"] == [0.0, 0.0, 0.0]
                 and tuple(e["hkl"]) == (2, 0, 0))
    cw = sorted(f.omega_deg for f in bragg_flashes(_g_sample(entry), LAMBDA_A))
    ccw = sorted(f.omega_deg for f in
                 bragg_flashes(_g_sample(entry), LAMBDA_A, omega_sign=DCT_OMEGA_SIGN_CCW))
    assert max(abs(a - b) for a, b in zip(cw, ccw)) < 1e-9
    assert abs((cw[0] + cw[1]) - 360.0) < 1e-9        # the symmetry that hides it
