"""Dislocation contrast factors in the hexagonal crystal system.

Implements Dragomir & Ungár, *J. Appl. Cryst.* **35** (2002) 556-564 — the
hexagonal companion to the cubic ANIZC calculation in :mod:`contrast_factor`.
The single-dislocation Stroh core (:func:`contrast_factor.single_contrast_factor`)
and the crystal→Cartesian orthogonalisation matrix are reused unchanged; what this
module adds is hexagonal-specific:

* :func:`hexagonal_stiffness` — the 5-constant (C11,C12,C13,C33,C44) Voigt tensor.
* Miller-Bravais (4-index) → Cartesian for plane normals ``(hkil)`` and directions
  ``[uvtw]``.
* The 11 sub-slip-systems of Table 1 (basal / prismatic / pyramidal; edge + screw).
* The slip-system **average** contrast factor C̄ over the hexagonal point-group
  orbit of each system (paper eqn 5), b²-weighting handled in
  :mod:`burgers_population`.
* The parabolic model ``C̄_{hk.l} = C̄_{hk.0}(1 + q₁x + q₂x²)`` with
  ``x = (2/3)(l/ga)²`` (paper eqn 8) and the fit that extracts ``(C̄_{hk.0},q₁,q₂)``
  — the three numbers compiled per material in the paper's Table 2.

Conventions, differentiability and device support match :mod:`contrast_factor`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Sequence, Tuple

import numpy as np
import torch

from .contrast_factor import single_contrast_factor, _crystal_A_matrix, _to_cartesian

__all__ = [
    "hexagonal_stiffness",
    "mb_plane_to_hkl",
    "mb_direction_to_uvw",
    "HexSlipSystem",
    "hex_slip_systems",
    "subsystem_contrast_factor",
    "HexCbarModel",
    "fit_hex_cbar",
    "BURGERS_A",
    "BURGERS_C",
    "BURGERS_CA",
]


# ---------------------------------------------------------------------------
# Stiffness and Miller-Bravais geometry
# ---------------------------------------------------------------------------

def hexagonal_stiffness(
    c11: float, c12: float, c13: float, c33: float, c44: float, *,
    dtype: torch.dtype = torch.float64, device=None,
) -> torch.Tensor:
    """6×6 Voigt stiffness of a hexagonal crystal (``C66 = (C11-C12)/2``)."""
    device = torch.device("cpu") if device is None else device
    t = lambda x: torch.as_tensor(x, dtype=dtype, device=device)
    c11, c12, c13, c33, c44 = t(c11), t(c12), t(c13), t(c33), t(c44)
    c66 = (c11 - c12) / 2.0
    z = torch.zeros((), dtype=dtype, device=device)
    rows = [
        torch.stack([c11, c12, c13, z, z, z]),
        torch.stack([c12, c11, c13, z, z, z]),
        torch.stack([c13, c13, c33, z, z, z]),
        torch.stack([z, z, z, c44, z, z]),
        torch.stack([z, z, z, z, c44, z]),
        torch.stack([z, z, z, z, z, c66]),
    ]
    return torch.stack(rows, dim=0)


def mb_plane_to_hkl(hkil: Sequence[int]) -> Tuple[int, int, int]:
    """Miller-Bravais plane ``(hkil)`` → 3-index ``(hkl)`` (drop the redundant ``i``)."""
    h, k, i, l = hkil
    assert h + k + i == 0, f"(hkil) must satisfy h+k+i=0, got {hkil}"
    return (int(h), int(k), int(l))


def mb_direction_to_uvw(uvtw: Sequence[int]) -> Tuple[float, float, float]:
    """Miller-Bravais direction ``[uvtw]`` → 3-index ``[UVW]`` (``U=u-t, V=v-t, W=w``)."""
    u, v, t, w = uvtw
    assert u + v + t == 0, f"[uvtw] must satisfy u+v+t=0, got {uvtw}"
    return (float(u - t), float(v - t), float(w))


# ---------------------------------------------------------------------------
# Hexagonal proper point group (D6 / 622): 12 Cartesian rotations
# ---------------------------------------------------------------------------

def _hex_proper_rotations(
    A: torch.Tensor, *, dtype: torch.dtype, device,
) -> torch.Tensor:
    """The 12 proper rotations of the hexagonal point group, in Cartesian axes.

    Generated by closure of the 6-fold about ``c`` (≡ Cartesian z in the
    orthogonalisation convention) and a 2-fold about the ``a₁`` direction. C is
    inversion-invariant, so the 12 proper rotations span the powder average (the
    12 improper operations give identical contrast factors).
    """
    # 6-fold about z
    th = math.pi / 3.0
    c, s = math.cos(th), math.sin(th)
    C6 = torch.tensor([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]],
                      dtype=dtype, device=device)
    # 2-fold about the Cartesian a₁ direction (= A · [1,0,0], normalised)
    a1 = (A @ torch.tensor([1.0, 0.0, 0.0], dtype=dtype, device=device))
    n = a1 / torch.linalg.norm(a1)
    C2 = 2.0 * torch.outer(n, n) - torch.eye(3, dtype=dtype, device=device)

    gens = [C6, C2]
    group = [torch.eye(3, dtype=dtype, device=device)]

    def _seen(M):
        return any(torch.allclose(M, G, atol=1e-9) for G in group)

    changed = True
    while changed:
        changed = False
        for G in list(group):
            for g in gens:
                M = g @ G
                if not _seen(M):
                    group.append(M)
                    changed = True
    return torch.stack(group, dim=0)


# ---------------------------------------------------------------------------
# Table 1 — the 11 hexagonal sub-slip-systems
# ---------------------------------------------------------------------------

#: Burgers-vector type representatives (Miller-Bravais [uvtw]).
BURGERS_A = (2, -1, -1, 0)      # ⟨a⟩  = ⅓⟨2̄110⟩
BURGERS_C = (0, 0, 0, 1)        # ⟨c⟩  = ⟨0001⟩
BURGERS_CA = (2, -1, -1, 3)     # ⟨c+a⟩ = ⅓⟨2̄113⟩


@dataclass(frozen=True)
class HexSlipSystem:
    """One hexagonal sub-slip-system (Table 1)."""
    name: str
    character: str                       # "edge" | "screw"
    btype: str                           # "a" | "c" | "c+a"
    burgers_uvtw: Tuple[int, int, int, int]
    plane_hkil: Tuple[int, int, int, int] | None   # None for screw


_HEX_SLIP: List[HexSlipSystem] = [
    # --- edge ---
    HexSlipSystem("BE",   "edge", "a",   BURGERS_A,  (0, 0, 0, 1)),    # basal {0001}⟨a⟩
    HexSlipSystem("PrE",  "edge", "a",   BURGERS_A,  (0, 1, -1, 0)),   # prismatic {1̄010}⟨a⟩
    HexSlipSystem("Pr2E", "edge", "c",   BURGERS_C,  (0, 1, -1, 0)),   # prismatic {1̄010}⟨c⟩
    HexSlipSystem("Pr3E", "edge", "c+a", BURGERS_CA, (0, 1, -1, 0)),   # prismatic {1̄010}⟨c+a⟩
    HexSlipSystem("PyE",  "edge", "a",   (-1, 2, -1, 0), (1, 0, -1, 1)),   # pyramidal {1̄011}⟨a⟩
    HexSlipSystem("Py2E", "edge", "c+a", BURGERS_CA, (-2, 1, 1, 2)),   # pyramidal {2̄112}⟨c+a⟩
    HexSlipSystem("PyE3", "edge", "c+a", BURGERS_CA, (1, 1, -2, 1)),   # pyramidal {112̄1}⟨c+a⟩
    HexSlipSystem("PyE4", "edge", "c+a", BURGERS_CA, (1, 0, -1, 1)),   # pyramidal {1̄011}⟨c+a⟩
    # --- screw (line ∥ b; slip plane immaterial to C) ---
    HexSlipSystem("S1", "screw", "a",   BURGERS_A,  None),
    HexSlipSystem("S2", "screw", "c+a", BURGERS_CA, None),
    HexSlipSystem("S3", "screw", "c",   BURGERS_C,  None),
]


def hex_slip_systems() -> List[HexSlipSystem]:
    """The 11 hexagonal sub-slip-systems of Dragomir & Ungár (2002) Table 1."""
    return list(_HEX_SLIP)


# ---------------------------------------------------------------------------
# Averaged contrast factor of a sub-slip-system
# ---------------------------------------------------------------------------

def _orthogonal_unit(v: torch.Tensor) -> torch.Tensor:
    """Some unit vector orthogonal to ``v`` (for the screw frame normal)."""
    ref = torch.tensor([1.0, 0.0, 0.0], dtype=v.dtype, device=v.device)
    if torch.abs(torch.dot(v, ref) / torch.linalg.norm(v)) > 0.9:
        ref = torch.tensor([0.0, 1.0, 0.0], dtype=v.dtype, device=v.device)
    w = ref - (ref @ v) / (v @ v) * v
    return w / torch.linalg.norm(w)


#: C66-perturbation fractions used to lift the basal-isotropic degeneracy.
_DEGEN_DELTAS = (0.02, 0.01)


def _robust_single_cf(C6, *, burgers, slip_normal, line, g, n_phi):
    """``single_contrast_factor`` with a fallback for the basal-isotropic limit.

    When the dislocation line lies along the hexagonal ``c`` axis (PrE edge, S3
    screw), the basal plane is *exactly* elastically isotropic, so the sextic
    roots are degenerate and the simple-eigenvector Stroh solve is unreliable
    (it raises). We then break the basal isotropy by scaling ``C66`` by ``(1+δ)``
    at two small ``δ`` and linearly extrapolate the contrast factor to ``δ→0`` —
    the physical limit. Stays differentiable (a linear combination of two
    differentiable evaluations).
    """
    try:
        return single_contrast_factor(C6, burgers=burgers, slip_normal=slip_normal,
                                      line=line, g=g, n_phi=n_phi)
    except ValueError:
        E55 = torch.zeros_like(C6)
        E55[5, 5] = 1.0
        c66 = C6[5, 5]
        d1, d2 = _DEGEN_DELTAS
        c_d1 = single_contrast_factor(C6 + d1 * c66 * E55, burgers=burgers,
                                      slip_normal=slip_normal, line=line, g=g, n_phi=n_phi)
        c_d2 = single_contrast_factor(C6 + d2 * c66 * E55, burgers=burgers,
                                      slip_normal=slip_normal, line=line, g=g, n_phi=n_phi)
        # linear extrapolation to δ=0:  c(0) = c_d2 + (c_d1-c_d2)/(d1-d2)·(0-d2)
        return c_d2 + (c_d1 - c_d2) / (d1 - d2) * (-d2)


def subsystem_contrast_factor(
    C6: torch.Tensor,
    crystal,
    system: HexSlipSystem,
    hkil: Sequence[int],
    *,
    n_phi: int = 360,
) -> torch.Tensor:
    """Average contrast factor C̄ of one sub-slip-system for reflection ``(hkil)``.

    Averages the individual Stroh contrast factor over the hexagonal point-group
    orbit of the system's representative (Burgers, plane) pair (paper eqn 5).
    """
    dtype, device = C6.dtype, C6.device
    A = _crystal_A_matrix(crystal, dtype=dtype, device=device)

    # representative Burgers (direct) and g (reciprocal) in Cartesian
    uvw = mb_direction_to_uvw(system.burgers_uvtw)
    b0 = _to_cartesian(torch.tensor(uvw, dtype=dtype, device=device), A, "direct")
    hkl = mb_plane_to_hkl(list(hkil) if len(hkil) == 4 else
                          (hkil[0], hkil[1], -(hkil[0] + hkil[1]), hkil[2]))
    g0 = _to_cartesian(torch.tensor([float(x) for x in hkl], dtype=dtype, device=device),
                       A, "reciprocal")

    if system.character == "screw":
        n0 = _orthogonal_unit(b0)            # frame normal; C is plane-independent
    else:
        nhkl = mb_plane_to_hkl(system.plane_hkil)
        n0 = _to_cartesian(torch.tensor([float(x) for x in nhkl], dtype=dtype, device=device),
                           A, "reciprocal")

    # Average over the point-group orbit of the slip system for a FIXED reflection
    # g₀ (paper eqn 5): rotate (Burgers, plane normal) only — rotating g too would
    # leave C invariant (frame-independent) and defeat the average.
    rotations = _hex_proper_rotations(A, dtype=dtype, device=device)
    vals = []
    for R in rotations:
        b = R @ b0
        n = R @ n0
        if system.character == "screw":
            line = b
        else:
            line = torch.linalg.cross(n, b)
        vals.append(_robust_single_cf(
            C6, burgers=b, slip_normal=n, line=line, g=g0, n_phi=n_phi))
    return torch.stack(vals).mean()


# ---------------------------------------------------------------------------
# Parabolic model  C̄_{hk.l} = C̄_{hk.0} (1 + q₁ x + q₂ x²),  x = (2/3)(l/ga)²
# ---------------------------------------------------------------------------

#: Reflections spanning x ∈ [0, (2/3)(c/a)²] (distinct angles δ between g and c).
_FIT_REFLECTIONS = [
    (1, 0, -1, 0), (1, 0, -1, 1), (1, 0, -1, 2), (1, 0, -1, 3),
    (1, 1, -2, 0), (1, 1, -2, 2), (2, 0, -2, 1), (2, 0, -2, 3),
    (1, 0, -1, 4), (0, 0, 0, 1),
]


def _x_invariant(crystal, hkil, A, dtype, device) -> float:
    """x = (2/3)(l/(g·a))² for reflection ``(hkil)`` — the parabola variable."""
    hkl = mb_plane_to_hkl(hkil)
    g = _to_cartesian(torch.tensor([float(x) for x in hkl], dtype=dtype, device=device),
                      A, "reciprocal")
    g_mag = float(torch.linalg.norm(g))
    a = float(crystal.lattice.a)
    l = hkl[2]
    return (2.0 / 3.0) * (l / (g_mag * a)) ** 2


@dataclass
class HexCbarModel:
    """Fitted hexagonal contrast-factor parabola for one sub-slip-system."""
    name: str
    cbar_hk0: float          # C̄_{hk.0} (x = 0 intercept)
    q1: float
    q2: float
    residual_norm: float
    n_reflections: int

    def __call__(self, x: float) -> float:
        return self.cbar_hk0 * (1.0 + self.q1 * x + self.q2 * x * x)


def fit_hex_cbar(
    C6: torch.Tensor,
    crystal,
    system: HexSlipSystem,
    *,
    reflections: Sequence[Sequence[int]] | None = None,
    n_phi: int = 360,
) -> HexCbarModel:
    """Fit ``C̄_{hk.l} = C̄_{hk.0}(1 + q₁x + q₂x²)`` for one sub-slip-system.

    Computes the slip-system-averaged C̄ over a set of reflections spanning the
    full range of ``x`` and least-squares fits the parabola, returning the three
    Dragomir-Ungár parameters ``(C̄_{hk.0}, q₁, q₂)`` (their Table 2). The fit is
    near-exact (residual → 0) because the model is analytic (Ungár & Tichy 1999) —
    a non-trivial residual flags a geometry/averaging bug.
    """
    dtype, device = C6.dtype, C6.device
    A = _crystal_A_matrix(crystal, dtype=dtype, device=device)
    refl = list(reflections) if reflections is not None else _FIT_REFLECTIONS

    xs, cs = [], []
    for hkil in refl:
        xs.append(_x_invariant(crystal, hkil, A, dtype, device))
        cs.append(float(subsystem_contrast_factor(
            C6, crystal, system, hkil, n_phi=n_phi)))
    x = np.asarray(xs, dtype=float)
    c = np.asarray(cs, dtype=float)

    # C̄ = c0 + c1 x + c2 x²  → c0 = C̄_{hk.0}, q1 = c1/c0, q2 = c2/c0
    M = np.column_stack([np.ones_like(x), x, x * x])
    coef, *_ = np.linalg.lstsq(M, c, rcond=None)
    c0, c1, c2 = (float(coef[0]), float(coef[1]), float(coef[2]))
    resid = float(np.linalg.norm(c - M @ coef))
    q1 = c1 / c0 if c0 != 0 else float("nan")
    q2 = c2 / c0 if c0 != 0 else float("nan")
    return HexCbarModel(name=system.name, cbar_hk0=c0, q1=q1, q2=q2,
                        residual_norm=resid, n_reflections=len(refl))
