"""Integration tests comparing Python forward model against C executables.

Runs the verified C executables (ForwardSimulationCompressed, simulateNF)
and compares their spot predictions against the Python HEDMForwardModel.

These tests validate the Python physics against battle-tested C code.

Run with:
    cd /Users/hsharma/opt/MIDAS/fwd_sim
    python -m pytest tests/test_c_comparison.py -v -s

Requires:
    - Built C executables in /Users/hsharma/opt/MIDAS/build/bin/
    - ~10 seconds per test
"""

import math
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import pytest
import torch

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from hedm_forward import HEDMForwardModel, HEDMGeometry, TriVoxelConfig

MIDAS_HOME = Path("/Users/hsharma/opt/MIDAS")
BUILD_BIN = MIDAS_HOME / "build" / "bin"

# Skip all tests if executables not found
pytestmark = pytest.mark.skipif(
    not (BUILD_BIN / "ForwardSimulationCompressed").exists()
    or not (BUILD_BIN / "GetHKLList").exists()
    or not (BUILD_BIN / "simulateNF").exists(),
    reason="C executables not built",
)

DEG2RAD = math.pi / 180.0
RAD2DEG = 180.0 / math.pi


# ---------------------------------------------------------------------------
#  Helper: parse hkls.csv generated by GetHKLList
# ---------------------------------------------------------------------------
def parse_hkls_csv(path):
    """Parse hkls.csv -> (hkls_cart (M,3), thetas (M,), hkls_int (M,3), ring_nrs (M,))."""
    data = np.loadtxt(path, skiprows=1)
    if data.ndim == 1:
        data = data.reshape(1, -1)
    hkls_int = data[:, 0:3]   # h, k, l integers
    ring_nrs = data[:, 4]     # RingNr
    g_cart = data[:, 5:8]     # g1, g2, g3 (Cartesian reciprocal space)
    theta_deg = data[:, 8]    # Theta in degrees
    return (
        torch.tensor(g_cart, dtype=torch.float64),
        torch.tensor(theta_deg * DEG2RAD, dtype=torch.float64),
        torch.tensor(hkls_int, dtype=torch.float64),
        ring_nrs,
    )


# ---------------------------------------------------------------------------
#  Helper: parse SpotMatrixGen.csv from ForwardSimulationCompressed
# ---------------------------------------------------------------------------
def parse_spot_matrix_gen(path):
    """Parse SpotMatrixGen.csv.

    Returns dict with arrays:
        grain_id, omega_deg, det_hor, det_vert, eta_deg, ring_nr, theta_deg, scan_nr
    """
    data = np.loadtxt(path, skiprows=1, delimiter="\t")
    if data.ndim == 1:
        data = data.reshape(1, -1)
    return {
        "grain_id": data[:, 0].astype(int),
        "omega_deg": data[:, 2],
        "det_hor": data[:, 3],
        "det_vert": data[:, 4],
        "eta_deg": data[:, 6],
        "ring_nr": data[:, 7].astype(int),
        "theta_deg": data[:, 10],
        "scan_nr": data[:, 12].astype(int),
        "ring_rad": data[:, 13],
    }


# ---------------------------------------------------------------------------
#  Helper: parse SimulatedSpots.csv from simulateNF
# ---------------------------------------------------------------------------
def parse_simulated_spots_csv(path):
    """Parse SimulatedSpots.csv from simulateNF.

    Returns dict with arrays:
        vox_nr, dist_nr, frame_nr, hor_px, ver_px, omega_raw
    """
    data = np.loadtxt(path, skiprows=1, delimiter="\t")
    if data.ndim == 1:
        data = data.reshape(1, -1)
    return {
        "vox_nr": data[:, 0].astype(int),
        "dist_nr": data[:, 1].astype(int),
        "frame_nr": data[:, 2].astype(int),
        "hor_px": data[:, 3],
        "ver_px": data[:, 4],
        "omega_raw": data[:, 5],
    }


# ===================================================================
#  Test: FF-HEDM  (ForwardSimulationCompressed vs Python)
# ===================================================================

class TestFFComparison:
    """Compare ForwardSimulationCompressed SpotMatrixGen.csv against Python."""

    @pytest.fixture
    def ff_work_dir(self, tmp_path):
        """Create a temp directory with minimal FF-HEDM simulation setup."""
        work = tmp_path / "ff_test"
        work.mkdir()

        # Known orientation: 3 Euler angles (degrees)
        euler_deg = np.array([45.0, 30.0, 60.0])
        euler_rad = euler_deg * DEG2RAD

        # Compute orientation matrix from Euler angles (ZXZ convention)
        c0, c1, c2 = np.cos(euler_rad)
        s0, s1, s2 = np.sin(euler_rad)
        O = np.array([
            [c0*c2 - s0*c1*s2, -s0*c1*c2 - c0*s2,  s0*s1],
            [s0*c2 + c0*c1*s2,  c0*c1*c2 - s0*s2,  -c0*s1],
            [s1*s2,              s1*c2,               c1],
        ])

        # Grain position
        pos_um = np.array([0.0, 0.0, 0.0])  # at origin for simplicity

        # Lattice: cubic Au
        latc = [4.08, 4.08, 4.08, 90.0, 90.0, 90.0]
        wl = 0.172979
        Lsd = 1000000.0  # 1 meter (far-field)
        px_size = 200.0  # um
        y_bc, z_bc = 1024.0, 1024.0
        n_pix = 2048
        omega_start, omega_step = 0.0, 0.25
        n_frames = 1440  # 360 / 0.25

        # Write GrainsSim.csv
        grain_file = work / "GrainsSim.csv"
        with open(grain_file, "w") as f:
            f.write("%NumGrains 1\n")
            f.write("%BeamCenter 0.0\n")
            f.write("%BeamThickness 10000.0\n")
            f.write("%GlobalPosition 0.0\n")
            f.write("%NumPhases 1\n")
            f.write("%PhaseInfo\n")
            f.write(f"%\tSpaceGroup:225\n")
            lstr = " ".join(f"{v:.6f}" for v in latc)
            f.write(f"%\tLattice Parameter: {lstr}\n")
            f.write("%GrainID\tO11\tO12\tO13\tO21\tO22\tO23\tO31\tO32\tO33"
                    "\tX\tY\tZ\ta\tb\tc\talpha\tbeta\tgamma\n")
            vals = list(O.flatten()) + list(pos_um) + latc
            line = "1\t" + "\t".join(f"{v:.6f}" for v in vals)
            f.write(line + "\n")

        # Write parameter file
        param_file = work / "params_ff.txt"
        with open(param_file, "w") as f:
            f.write(f"LatticeParameter {' '.join(str(v) for v in latc)}\n")
            f.write(f"Wavelength {wl}\n")
            f.write(f"SpaceGroup 225\n")
            f.write(f"Lsd {Lsd}\n")
            f.write(f"BC {y_bc} {z_bc}\n")
            f.write(f"px {px_size}\n")
            f.write(f"NrPixels {n_pix}\n")
            f.write(f"tx 0\n")
            f.write(f"ty 0\n")
            f.write(f"tz 0\n")
            f.write(f"Wedge 0\n")
            f.write(f"OmegaStart {omega_start}\n")
            f.write(f"OmegaEnd {omega_start + omega_step * n_frames}\n")
            f.write(f"OmegaStep {omega_step}\n")
            f.write(f"MaxRingRad {Lsd * 0.3}\n")
            f.write(f"InFileName {grain_file}\n")
            f.write(f"OutFileName {work / 'sim_out'}\n")
            f.write(f"WriteSpots 1\n")
            f.write(f"WriteImage 0\n")
            f.write(f"nScans 1\n")
            f.write(f"PeakIntensity 2000\n")
            f.write(f"GaussWidth 2.0\n")

        return {
            "work": work,
            "param_file": param_file,
            "euler_deg": euler_deg,
            "euler_rad": euler_rad,
            "orient_mat": O,
            "pos_um": pos_um,
            "latc": latc,
            "wl": wl,
            "Lsd": Lsd,
            "px": px_size,
            "y_bc": y_bc,
            "z_bc": z_bc,
            "n_pix": n_pix,
            "omega_start": omega_start,
            "omega_step": omega_step,
            "n_frames": n_frames,
        }

    def test_ff_spots_match_c(self, ff_work_dir):
        """Run ForwardSimulationCompressed and compare spot positions."""
        cfg = ff_work_dir

        # Step 1: Generate HKL list
        result = subprocess.run(
            [str(BUILD_BIN / "GetHKLList"), str(cfg["param_file"])],
            cwd=str(cfg["work"]),
            capture_output=True, text=True, timeout=30,
        )
        assert result.returncode == 0, f"GetHKLList failed:\n{result.stderr}"

        hkls_file = cfg["work"] / "hkls.csv"
        assert hkls_file.exists(), "hkls.csv not generated"
        hkls_cart, thetas, hkls_int, ring_nrs = parse_hkls_csv(hkls_file)
        n_hkls = hkls_cart.shape[0]
        print(f"  {n_hkls} HKL reflections loaded")

        # Step 2: Run C forward simulation
        result = subprocess.run(
            [str(BUILD_BIN / "ForwardSimulationCompressed"),
             str(cfg["param_file"]), "1"],
            cwd=str(cfg["work"]),
            capture_output=True, text=True, timeout=60,
        )
        assert result.returncode == 0, f"ForwardSimulation failed:\n{result.stderr}"

        spot_file = cfg["work"] / "SpotMatrixGen.csv"
        assert spot_file.exists(), "SpotMatrixGen.csv not generated"
        c_spots = parse_spot_matrix_gen(spot_file)
        n_c_spots = len(c_spots["omega_deg"])
        print(f"  C produced {n_c_spots} spots")
        assert n_c_spots > 0, "C simulation produced no spots"

        # Step 3: Run Python forward model
        geometry = HEDMGeometry(
            Lsd=cfg["Lsd"], y_BC=cfg["y_bc"], z_BC=cfg["z_bc"], px=cfg["px"],
            omega_start=cfg["omega_start"], omega_step=cfg["omega_step"],
            n_frames=cfg["n_frames"],
            n_pixels_y=cfg["n_pix"], n_pixels_z=cfg["n_pix"],
            min_eta=6.0, wavelength=cfg["wl"],
        )
        model = HEDMForwardModel(
            hkls=hkls_cart, thetas=thetas, geometry=geometry,
            hkls_int=hkls_int, device=torch.device("cpu"),
        )

        euler = torch.tensor(cfg["euler_rad"], dtype=torch.float64).unsqueeze(0)  # (1, 3)
        pos = torch.tensor(cfg["pos_um"], dtype=torch.float64).unsqueeze(0)       # (1, 3)
        spots = model(euler, pos)

        # Extract valid Python spots
        py_omega = spots.omega[spots.valid > 0.5].numpy() * RAD2DEG
        py_eta = spots.eta[spots.valid > 0.5].numpy() * RAD2DEG
        py_y = spots.y_pixel[spots.valid > 0.5].numpy()
        py_z = spots.z_pixel[spots.valid > 0.5].numpy()

        n_py_spots = len(py_omega)
        print(f"  Python produced {n_py_spots} valid spots")
        assert n_py_spots > 0, "Python produced no valid spots"

        # Step 4: Match spots by (omega, ring_nr/eta proximity)
        # For each C spot, find the closest Python spot in omega-eta space
        matched = 0
        omega_errors = []
        eta_errors = []
        y_errors = []
        z_errors = []

        for i in range(n_c_spots):
            c_ome = c_spots["omega_deg"][i]
            c_eta = c_spots["eta_deg"][i]
            c_y = c_spots["det_hor"][i]
            c_z = c_spots["det_vert"][i]

            # Find closest Python spot in (omega, eta) space
            ome_diff = np.abs(py_omega - c_ome)
            eta_diff = np.abs(py_eta - c_eta)
            # Handle eta wrapping
            eta_diff = np.minimum(eta_diff, 360.0 - eta_diff)
            dist = np.sqrt(ome_diff**2 + eta_diff**2)

            best = np.argmin(dist)
            if dist[best] < 1.0:  # within 1 degree in (omega, eta) space
                matched += 1
                omega_errors.append(ome_diff[best])
                eta_errors.append(eta_diff[best])
                y_errors.append(abs(py_y[best] - c_y))
                z_errors.append(abs(py_z[best] - c_z))

        match_frac = matched / n_c_spots if n_c_spots > 0 else 0
        print(f"  Matched {matched}/{n_c_spots} C spots ({match_frac:.1%})")

        if matched > 0:
            print(f"  Omega error: mean={np.mean(omega_errors):.4f} deg, "
                  f"max={np.max(omega_errors):.4f} deg")
            print(f"  Eta error:   mean={np.mean(eta_errors):.4f} deg, "
                  f"max={np.max(eta_errors):.4f} deg")
            print(f"  Y pixel err: mean={np.mean(y_errors):.2f} px, "
                  f"max={np.max(y_errors):.2f} px")
            print(f"  Z pixel err: mean={np.mean(z_errors):.2f} px, "
                  f"max={np.max(z_errors):.2f} px")

        # Assertions
        assert match_frac > 0.90, (
            f"Only {match_frac:.1%} of C spots matched to Python. "
            "Possible convention mismatch."
        )
        if matched > 0:
            assert np.max(omega_errors) < 0.5, (
                f"Max omega error {np.max(omega_errors):.4f} deg exceeds 0.5 deg"
            )
            assert np.max(eta_errors) < 0.5, (
                f"Max eta error {np.max(eta_errors):.4f} deg exceeds 0.5 deg"
            )
            # Pixel errors may be larger due to position/magnification
            # but for FF (Lsd=1m) with grain at origin, should be very small
            assert np.mean(y_errors) < 2.0, (
                f"Mean Y pixel error {np.mean(y_errors):.2f} too large"
            )
            assert np.mean(z_errors) < 2.0, (
                f"Mean Z pixel error {np.mean(z_errors):.2f} too large"
            )


# ===================================================================
#  Test: NF-HEDM  (simulateNF vs Python)
# ===================================================================

class TestNFComparison:
    """Compare simulateNF SimulatedSpots.csv against Python model."""

    @pytest.fixture
    def nf_work_dir(self, tmp_path):
        """Create a temp directory with minimal NF-HEDM simulation setup."""
        work = tmp_path / "nf_test"
        work.mkdir()

        # Known orientation
        euler_deg = np.array([45.0, 30.0, 60.0])
        euler_rad = euler_deg * DEG2RAD

        # Single voxel at origin
        voxel_x, voxel_y = 0.0, 0.0
        edge_len = 5.0  # > px (1.48) so triangle rasterization is exercised
        ud = 1.0

        # Lattice: cubic Au
        latc = [4.08, 4.08, 4.08, 90.0, 90.0, 90.0]
        wl = 0.172979
        Lsd = 5000.0  # 5 mm (near-field)
        px_size = 1.48
        y_bc, z_bc = 1024.0, 12.0
        n_pix = 2048
        omega_start = 0.0
        omega_step = 0.25
        n_frames = 1440

        # Write .mic file (single voxel)
        mic_file = work / "test.mic"
        with open(mic_file, "w") as f:
            f.write("%TriEdgeSize 0.500000\n")
            f.write("%NumPhases 1\n")
            f.write("%GlobalPosition 0.000000\n")
            f.write("%OrientationRowNr OrientationID RunTime X Y TriEdgeSize "
                    "UpDown Eul1 Eul2 Eul3 Confidence PhaseNr\n")
            # .mic stores Euler angles in RADIANS. simulateNF multiplies by
            # hardcoded rad2deg. CRITICAL: write with full double precision
            # to avoid truncation errors that cascade through the solver.
            f.write(f"1 1 0 {voxel_x:.6f} {voxel_y:.6f} {edge_len:.6f} "
                    f"{ud:.6f} {euler_rad[0]:.17e} {euler_rad[1]:.17e} "
                    f"{euler_rad[2]:.17e} 1.000000 1\n")

        # Write parameter file
        param_file = work / "params_nf.txt"
        with open(param_file, "w") as f:
            f.write(f"LatticeParameter {' '.join(str(v) for v in latc)}\n")
            f.write(f"Wavelength {wl}\n")
            f.write(f"SpaceGroup 225\n")
            f.write(f"nDistances 1\n")
            f.write(f"Lsd {Lsd}\n")
            f.write(f"BC {y_bc} {z_bc}\n")
            f.write(f"tx 0\n")
            f.write(f"ty 0\n")
            f.write(f"tz 0\n")
            f.write(f"Wedge 0\n")
            f.write(f"px {px_size}\n")
            f.write(f"NrPixels {n_pix}\n")
            f.write(f"MaxRingRad {Lsd * 0.5}\n")
            f.write(f"OmegaStart {omega_start}\n")
            f.write(f"OmegaStep {omega_step}\n")
            f.write(f"OmegaRange {omega_start} {omega_start + omega_step * n_frames}\n")
            f.write(f"BoxSize -100000 100000 -100000 100000\n")
            f.write(f"StartNr 0\n")
            f.write(f"EndNr {n_frames - 1}\n")
            f.write(f"ExcludePoleAngle 6\n")
            f.write(f"NrFilesPerDistance {n_frames}\n")
            f.write(f"SaveReducedOutput 0\n")
            f.write(f"WriteImage 0\n")
            f.write(f"OnlySpotsInfo 0\n")

        return {
            "work": work,
            "param_file": param_file,
            "mic_file": mic_file,
            "euler_deg": euler_deg,
            "euler_rad": euler_rad,
            "voxel_pos": np.array([voxel_x, voxel_y, 0.0]),
            "edge_len": edge_len,
            "ud": ud,
            "latc": latc,
            "wl": wl,
            "Lsd": Lsd,
            "px": px_size,
            "y_bc": y_bc,
            "z_bc": z_bc,
            "n_pix": n_pix,
            "omega_start": omega_start,
            "omega_step": omega_step,
            "n_frames": n_frames,
        }

    def test_nf_spots_match_c(self, nf_work_dir):
        """Run simulateNF and compare spot positions against Python."""
        cfg = nf_work_dir

        # Step 1: Run simulateNF (it calls GetHKLListNF internally)
        result = subprocess.run(
            [str(BUILD_BIN / "simulateNF"),
             str(cfg["param_file"]),
             str(cfg["mic_file"]),
             str(cfg["work"] / "sim_output"),
             "1"],
            cwd=str(cfg["work"]),
            capture_output=True, text=True, timeout=120,
        )
        assert result.returncode == 0, (
            f"simulateNF failed:\n{result.stdout}\n{result.stderr}"
        )

        spots_file = cfg["work"] / "SimulatedSpots.csv"
        assert spots_file.exists(), (
            f"SimulatedSpots.csv not generated. Files in dir: "
            f"{list(cfg['work'].iterdir())}"
        )
        c_spots = parse_simulated_spots_csv(spots_file)
        n_c_entries = len(c_spots["frame_nr"])
        print(f"  C produced {n_c_entries} pixel hits")
        assert n_c_entries > 0, "simulateNF produced no spots"

        # Extract unique spot centers: group by (vox_nr, approximate omega)
        # and take median pixel position
        c_omegas_unique = np.unique(c_spots["omega_raw"])
        c_spot_centers = []
        for ome in c_omegas_unique:
            mask = c_spots["omega_raw"] == ome
            c_spot_centers.append({
                "omega": ome,
                "hor_px": np.median(c_spots["hor_px"][mask]),
                "ver_px": np.median(c_spots["ver_px"][mask]),
                "frame_nr": int(np.median(c_spots["frame_nr"][mask])),
            })
        n_c_spots = len(c_spot_centers)
        print(f"  C unique spots (by omega): {n_c_spots}")

        # Step 2: Parse hkls.csv (generated by GetHKLListNF inside simulateNF)
        hkls_file = cfg["work"] / "hkls.csv"
        assert hkls_file.exists(), "hkls.csv not generated"
        hkls_cart, thetas, hkls_int, _ = parse_hkls_csv(hkls_file)
        print(f"  {hkls_cart.shape[0]} HKL reflections")

        # Step 3: Run Python forward model with triangular voxels
        geometry = HEDMGeometry(
            Lsd=cfg["Lsd"], y_BC=cfg["y_bc"], z_BC=cfg["z_bc"], px=cfg["px"],
            omega_start=cfg["omega_start"], omega_step=cfg["omega_step"],
            n_frames=cfg["n_frames"],
            n_pixels_y=cfg["n_pix"], n_pixels_z=cfg["n_pix"],
            min_eta=6.0, wavelength=cfg["wl"],
            flip_y=False,  # NF convention
        )
        model = HEDMForwardModel(
            hkls=hkls_cart, thetas=thetas, geometry=geometry,
            hkls_int=hkls_int, device=torch.device("cpu"),
        )

        # Read Euler angles back from the .mic file to get the EXACT same
        # float64 values that the C code reads (avoids truncation mismatch)
        with open(cfg["mic_file"]) as mf:
            for line in mf:
                if line.startswith("%"):
                    continue
                parts = line.split()
                euler_from_mic = [float(parts[7]), float(parts[8]), float(parts[9])]
                break
        euler = torch.tensor([euler_from_mic], dtype=torch.float64)  # (1, 3)
        centers = torch.tensor(cfg["voxel_pos"][:2], dtype=torch.float64).unsqueeze(0)
        tri = TriVoxelConfig(
            edge_lengths=torch.tensor([cfg["edge_len"]], dtype=torch.float64),
            ud=torch.tensor([cfg["ud"]], dtype=torch.float64),
        )

        py_hits = model.forward_nf_triangles(euler, centers, tri)
        n_py_hits = len(py_hits)
        print(f"  Python produced {n_py_hits} pixel hits (triangular voxels)")

        # Step 4: Compare pixel-for-pixel
        # Build sets of (dist, frame, y, z) for both C and Python
        c_set = set()
        for i in range(len(c_spots["frame_nr"])):
            c_set.add((
                int(c_spots["dist_nr"][i]),
                int(c_spots["frame_nr"][i]),
                int(round(c_spots["hor_px"][i])),
                int(round(c_spots["ver_px"][i])),
            ))

        py_set = set()
        for (vox, d, fr, y, z, ome) in py_hits:
            py_set.add((d, fr, y, z))

        # Compute overlap
        common = c_set & py_set
        only_c = c_set - py_set
        only_py = py_set - c_set

        n_common = len(common)
        n_c = len(c_set)
        n_py = len(py_set)

        match_frac = n_common / n_c if n_c > 0 else 0
        print(f"  C pixels: {n_c}, Python pixels: {n_py}, "
              f"Common: {n_common} ({match_frac:.1%})")
        if only_c:
            sample = list(only_c)[:5]
            print(f"  Only in C (sample): {sample}")
        if only_py:
            sample = list(only_py)[:5]
            print(f"  Only in Python (sample): {sample}")

        assert match_frac > 0.95, (
            f"Only {match_frac:.1%} pixel overlap. "
            f"C={n_c}, Py={n_py}, common={n_common}"
        )


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
