"""Assemble a self-contained XAF-HEDM design-report PDF.

Uses matplotlib's PdfPages (no external tooling): a summary page, a spec table,
and one page per figure.  Call :func:`generate_report` with your own content or
:func:`xaf_design_report` for the current design snapshot.
"""
from __future__ import annotations

import os
from typing import Dict, List, Optional, Sequence, Tuple


def generate_report(
    out_pdf: str,
    *,
    title: str,
    summary_lines: Sequence[str],
    spec_rows: Sequence[Tuple[str, str]],
    figure_paths: Sequence[str],
    figure_captions: Optional[Sequence[str]] = None,
) -> str:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.image as mpimg
    from matplotlib.backends.backend_pdf import PdfPages

    figure_captions = figure_captions or [""] * len(figure_paths)
    with PdfPages(out_pdf) as pdf:
        # --- summary page -------------------------------------------------
        fig = plt.figure(figsize=(8.5, 11))
        fig.text(0.5, 0.94, title, ha="center", va="top", fontsize=18, weight="bold")
        y = 0.86
        for line in summary_lines:
            fig.text(0.08, y, line, ha="left", va="top", fontsize=10, wrap=True)
            y -= 0.035
        fig.text(0.5, 0.04, "generated by midas_xaf.report", ha="center",
                 fontsize=7, color="gray")
        pdf.savefig(fig); plt.close(fig)

        # --- spec table page ---------------------------------------------
        fig = plt.figure(figsize=(8.5, 11))
        fig.text(0.5, 0.94, "Design spec", ha="center", fontsize=15, weight="bold")
        ax = fig.add_axes([0.08, 0.15, 0.84, 0.70]); ax.axis("off")
        tbl = ax.table(cellText=[list(r) for r in spec_rows],
                       colLabels=["parameter", "value"], loc="center",
                       cellLoc="left", colWidths=[0.35, 0.65])
        tbl.auto_set_font_size(False); tbl.set_fontsize(10); tbl.scale(1, 1.6)
        pdf.savefig(fig); plt.close(fig)

        # --- figure pages -------------------------------------------------
        for path, cap in zip(figure_paths, figure_captions):
            if not os.path.exists(path):
                print(f"[report] SKIPPED (missing): {path}")
                continue
            print(f"[report] embedding: {os.path.basename(path)}")
            fig = plt.figure(figsize=(8.5, 11))
            ax = fig.add_axes([0.05, 0.12, 0.90, 0.80]); ax.axis("off")
            ax.imshow(mpimg.imread(path))
            fig.text(0.5, 0.08, cap, ha="center", va="top", fontsize=9, wrap=True)
            fig.text(0.5, 0.955, os.path.basename(path), ha="center", fontsize=9,
                     color="gray")
            pdf.savefig(fig); plt.close(fig)
    return out_pdf


def xaf_design_report(out_pdf: str, figures_dir: str) -> str:
    """Current XAF-HEDM design snapshot (15 deg operating point)."""
    summary = [
        "Cross-Axis Faceted HEDM (XAF-HEDM): far-field HEDM through a cubic",
        "diamond anvil cell with a ~15 deg opening on all six faces. Two",
        "orthogonal-axis mountings are merged into one reciprocal-space",
        "reconstruction, each filling the other's missing cone. Registered by",
        "embedded high-Z fiducials; grain positions from Friedel pairs or",
        "point-focus scanning.",
        "",
        "Operating point (v1): 15 deg opening, ruby, 90 keV, Pilatus 2M CdTe.",
        "Predicted (merged): ~90 spots/grain, Friedel ~1.0, worst-direction",
        "strain sigma ~446 microstrain, cross-axis gain ~1.66x, reciprocal-space",
        "coverage ~28%, grain position ~25 um (box) / <1 um (point-focus).",
        "",
        "20 deg (v2 upside): ~312 spots/grain, ~216 microstrain, ~36% coverage.",
        "",
        "Mountings (15 deg / 20 deg strain sigma, microstrain):",
        "  1 mounting : 738 / 401    (coverage 18% / 24%)",
        "  2 mountings: 446 / 216    (coverage 28% / 36%)  <- core technique",
        "  3 mountings: 352 / 166    (coverage 31% / 40%)  <- optional refine",
        "The 1->2 step (orthogonal axis fills the blind cone) is the big win;",
        "the 3rd mounting adds ~1.3x strain + redundancy but little coverage.",
        "",
        "Honest limits: even merged only ~28% of reciprocal space is reached",
        "(narrow faceted access); 2theta<=7.5 deg makes the full 6-component",
        "strain tensor the hardest quantity. Novelty is the acquisition/loading",
        "geometry, not the strain capability (cf. Merkel & Yang 2014).",
    ]
    spec_rows = [
        ("Opening", "15 deg (v1); 20 deg = v2 upside"),
        ("Material", "Ruby (corundum) - rigid-safe, spot-rich"),
        ("Energy", "90 keV"),
        ("Detector", "Pilatus 2M, CdTe, 172 um, module gaps"),
        ("Distance", "~867 mm (auto, 15 deg)"),
        ("Beam", "box (<=~300 grains) / point-focus"),
        ("Grains in beam", "~200-400 (~11-14 um)"),
        ("Fiducials", "3+ high-Z (W/Au/Ta)"),
        ("Strain sigma (merged)", "~446 microstrain"),
        ("Cross-axis gain", "~1.66x"),
    ]
    figs = [
        ("strain_vs_opening.png", "Strain precision (CRLB) vs face opening; single vs merged."),
        ("coverage_1v2v3_mountings_15deg.png", "Coverage: 1 vs 2 vs 3 mountings (15 deg). 1->2 is the big win."),
        ("coverage_vs_opening_panel.png", "Reciprocal-space coverage vs opening; blind cones + merge."),
        ("coverage_geometry_20deg.png", "Direction coverage: mounting-1/2/both."),
        ("coverage_refl_ruby.png", "Ruby reflection coverage (spot-rich)."),
        ("coverage_refl_steel_fcc.png", "Steel FCC reflection coverage (spot-starved)."),
    ]
    paths = [os.path.join(figures_dir, f) for f, _ in figs]
    caps = [c for _, c in figs]
    return generate_report(out_pdf, title="XAF-HEDM Design Report",
                           summary_lines=summary, spec_rows=spec_rows,
                           figure_paths=paths, figure_captions=caps)
