#!/usr/bin/env python
"""Automated Benchmark Testing Suite for NF-HEDM.

This script:
1. Runs simulateNF on the Example mic to produce SpotsInfo.bin
2. Patches the parameter file with DataDirectory and SeedOrientations
3. Calls nf_MIDAS.py to run reconstruction (skipping image processing)
4. Compares reconstructed orientations against a reference mic file
"""

import argparse
import os
import sys
import subprocess
import shutil
import numpy as np
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Automated Benchmark Testing Suite for NF-HEDM"
    )
    parser.add_argument(
        "-nCPUs", type=int, default=4, help="Number of CPUs to use"
    )

    default_param_fn = (
        Path(__file__).resolve().parent.parent / "NF_HEDM" / "Example" / "ps_au.txt"
    )
    parser.add_argument(
        "-paramFN",
        type=str,
        default=str(default_param_fn),
        help="Path to the parameter file",
    )

    default_mic_fn = (
        Path(__file__).resolve().parent.parent / "NF_HEDM" / "Example" / "Au_txt.mic"
    )
    parser.add_argument(
        "-micFN",
        type=str,
        default=str(default_mic_fn),
        help="Path to the input mic file for simulation",
    )

    return parser.parse_args()


def get_midas_home():
    """Resolve MIDAS_HOME from env or script location."""
    return Path(
        os.environ.get("MIDAS_HOME", str(Path(__file__).resolve().parent.parent))
    )


def run_simulation(param_file, mic_file, nCPUs, work_dir):
    """Run simulateNF to produce SpotsInfo.bin."""
    midas_home = get_midas_home()
    simulate_bin = midas_home / "NF_HEDM" / "bin" / "simulateNF"

    if not simulate_bin.exists():
        print(f"Error: {simulate_bin} not found. Please compile first.")
        sys.exit(1)

    output_base = "recon"
    cmd = [
        str(simulate_bin),
        str(param_file),
        str(mic_file),
        output_base,
        str(nCPUs),
    ]
    print(f"\n{'='*60}")
    print(f"  Step 1: Running simulateNF")
    print(f"  Command: {' '.join(cmd)}")
    print(f"{'='*60}\n")

    result = subprocess.run(cmd, cwd=str(work_dir))
    if result.returncode != 0:
        print("Error: simulateNF failed.")
        sys.exit(1)

    spots_info = work_dir / "SpotsInfo.bin"
    if not spots_info.exists():
        print(f"Error: Expected SpotsInfo.bin not found in {work_dir}")
        sys.exit(1)

    print(f"SpotsInfo.bin generated: {spots_info} ({spots_info.stat().st_size} bytes)")
    return spots_info


def prepare_param_file(param_path, work_dir):
    """Create a working copy of the param file with DataDirectory, GrainsFile, and SeedOrientations set."""
    grains_file = work_dir / "grs.csv"
    if not grains_file.exists():
        print(f"Error: GrainsFile not found at {grains_file}")
        sys.exit(1)

    seed_orientations = work_dir / "seedOrientations.txt"

    # Read existing param file
    with open(param_path, "r") as f:
        lines = f.readlines()

    # Build new param file with required additions
    skip_keys = {"DataDirectory", "SeedOrientations", "GrainsFile"}
    test_param_file = work_dir / f"test_{param_path.name}"
    with open(test_param_file, "w") as f:
        for line in lines:
            stripped = line.split("#", 1)[0].strip()
            parts = stripped.split() if stripped else []
            key = parts[0] if parts else ""

            if key in skip_keys:
                continue
            f.write(line)

        # Add required parameters
        f.write(f"\nDataDirectory {work_dir}\n")
        f.write(f"GrainsFile {grains_file}\n")
        f.write(f"SeedOrientations {seed_orientations}\n")
        f.write(f"PrecomputedSpotsInfo 1\n")

    print(f"Created test parameter file: {test_param_file}")
    print(f"  GrainsFile:       {grains_file}")
    print(f"  SeedOrientations: {seed_orientations} (auto-generated by workflow)")
    return test_param_file


def run_nf_midas(param_file, nCPUs, work_dir):
    """Run nf_MIDAS.py with reconstruction flags."""
    midas_home = get_midas_home()
    nf_midas_script = midas_home / "NF_HEDM" / "workflows" / "nf_MIDAS.py"

    if not nf_midas_script.exists():
        print(f"Error: {nf_midas_script} not found.")
        sys.exit(1)

    cmd = [
        sys.executable,
        str(nf_midas_script),
        "-paramFN", param_file.name,
        "-nCPUs", str(nCPUs),
        "-ffSeedOrientations", "1",
        "-doImageProcessing", "0",
        "-refineParameters", "0",
        "-multiGridPoints", "0",
    ]

    print(f"\n{'='*60}")
    print(f"  Step 3: Running nf_MIDAS.py reconstruction")
    print(f"  Command: {' '.join(cmd)}")
    print(f"  Working dir: {work_dir}")
    print(f"{'='*60}\n")

    result = subprocess.run(cmd, cwd=str(work_dir))
    if result.returncode != 0:
        print("Error: nf_MIDAS.py failed.")
        sys.exit(1)

    print("\nnf_MIDAS.py completed successfully.")


def read_mic_file(mic_path):
    """Read a .mic file and return a dict keyed by (x, y) -> (eul1, eul2, eul3, confidence).

    Mic columns: OrientationRowNr(0) OrientationID(1) RunTime(2) X(3) Y(4)
                 TriEdgeSize(5) UpDown(6) Eul1(7) Eul2(8) Eul3(9) Confidence(10) PhaseNr(11)
    Euler angles are in degrees in the file.
    """
    voxels = {}
    with open(mic_path, 'r') as f:
        for line in f:
            if line.startswith('%') or line.strip() == '':
                continue
            vals = line.split()
            if len(vals) < 11:
                continue
            x = round(float(vals[3]), 4)
            y = round(float(vals[4]), 4)
            eul1 = float(vals[7])
            eul2 = float(vals[8])
            eul3 = float(vals[9])
            conf = float(vals[10])
            voxels[(x, y)] = (eul1, eul2, eul3, conf)
    return voxels


def compare_reconstructions(ref_mic_path, test_mic_path, sg_num=225):
    """Compare orientations between reference and test mic files.

    Matches voxels by (X, Y) position and computes misorientation angles.
    """
    # Import calcMiso from utils/
    midas_home = get_midas_home()
    sys.path.insert(0, str(midas_home / 'utils'))
    import calcMiso

    deg2rad = np.pi / 180.0
    rad2deg = 180.0 / np.pi

    print(f"\n{'='*60}")
    print(f"  Step 4: Comparing Reconstructions")
    print(f"  Reference: {ref_mic_path}")
    print(f"  Test:      {test_mic_path}")
    print(f"  SpaceGroup: {sg_num}")
    print(f"{'='*60}\n")

    ref_voxels = read_mic_file(ref_mic_path)
    test_voxels = read_mic_file(test_mic_path)

    print(f"Reference voxels: {len(ref_voxels)}")
    print(f"Test voxels:      {len(test_voxels)}")

    # Match by position
    matched = 0
    misorientations = []
    confidences_ref = []
    confidences_test = []

    for pos, (e1_r, e2_r, e3_r, c_r) in ref_voxels.items():
        if pos not in test_voxels:
            continue
        e1_t, e2_t, e3_t, c_t = test_voxels[pos]
        matched += 1

        euler_ref = np.array([e1_r * deg2rad, e2_r * deg2rad, e3_r * deg2rad])
        euler_test = np.array([e1_t * deg2rad, e2_t * deg2rad, e3_t * deg2rad])

        try:
            miso_rad, _ = calcMiso.GetMisOrientationAngle(euler_ref, euler_test, sg_num)
            miso_deg = miso_rad * rad2deg
            misorientations.append(miso_deg)
            confidences_ref.append(c_r)
            confidences_test.append(c_t)
        except Exception as e:
            # Skip voxels where misorientation calculation fails
            pass

    if not misorientations:
        print("Error: No matched voxels found for comparison.")
        return False

    miso = np.array(misorientations)
    conf_r = np.array(confidences_ref)
    conf_t = np.array(confidences_test)

    print(f"\nMatched voxels:   {matched}")
    print(f"Computed misos:   {len(miso)}")

    print(f"\n--- Misorientation Statistics (degrees) ---")
    print(f"  Mean:   {np.mean(miso):.4f}")
    print(f"  Median: {np.median(miso):.4f}")
    print(f"  Std:    {np.std(miso):.4f}")
    print(f"  Min:    {np.min(miso):.4f}")
    print(f"  Max:    {np.max(miso):.4f}")

    thresholds = [0.25, 1.0, 2.0, 5.0, 10.0]
    print(f"\n--- Fraction below threshold ---")
    for t in thresholds:
        frac = np.sum(miso < t) / len(miso) * 100
        print(f"  < {t:5.2f}°: {frac:6.2f}%")

    print(f"\n--- Confidence Statistics ---")
    print(f"  Reference  - Mean: {np.mean(conf_r):.4f}, Median: {np.median(conf_r):.4f}")
    print(f"  Test       - Mean: {np.mean(conf_t):.4f}, Median: {np.median(conf_t):.4f}")

    # Pass/fail: NF-HEDM should be very accurate
    pct_below_025 = np.sum(miso < 0.25) / len(miso) * 100
    passed = pct_below_025 > 80.0
    status = "PASSED" if passed else "FAILED"
    print(f"\n  Benchmark result: {status} ({pct_below_025:.1f}% of voxels < 0.25° misorientation)")
    return passed


def main():
    args = parse_args()
    param_path = Path(args.paramFN).resolve()
    mic_path = Path(args.micFN).resolve()

    if not param_path.exists():
        print(f"Error: Parameter file not found at {param_path}")
        sys.exit(1)
    if not mic_path.exists():
        print(f"Error: Mic file not found at {mic_path}")
        sys.exit(1)

    midas_home = get_midas_home()
    example_dir = midas_home / "NF_HEDM" / "Example"

    # Locate grs.csv in the Example directory
    grains_src = example_dir / "grs.csv"
    if not grains_src.exists():
        print(f"Error: GrainsFile not found at {grains_src}")
        sys.exit(1)

    # Create sim/ subdirectory (delete if exists for a clean run)
    work_dir = example_dir / "sim"
    if work_dir.exists():
        print(f"Removing previous sim directory: {work_dir}")
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True)

    # Copy the 3 source files into sim/
    shutil.copy2(param_path, work_dir / param_path.name)
    shutil.copy2(mic_path, work_dir / mic_path.name)
    shutil.copy2(grains_src, work_dir / "grs.csv")
    local_param = work_dir / param_path.name
    local_mic = work_dir / mic_path.name

    print(f"NF-HEDM Benchmark Test")
    print(f"  MIDAS home:  {midas_home}")
    print(f"  Param file:  {param_path} -> {local_param}")
    print(f"  Mic file:    {mic_path} -> {local_mic}")
    print(f"  Grains file: {grains_src} -> {work_dir / 'grs.csv'}")
    print(f"  Work dir:    {work_dir}")
    print(f"  CPUs:        {args.nCPUs}")

    # Step 1: Run simulation to produce SpotsInfo.bin
    run_simulation(local_param, local_mic, args.nCPUs, work_dir)

    # Step 2: Prepare param file with DataDirectory and SeedOrientations
    test_param_file = prepare_param_file(local_param, work_dir)

    # Step 3: Run nf_MIDAS.py reconstruction
    run_nf_midas(test_param_file, args.nCPUs, work_dir)

    # Step 4: Compare reconstructions
    ref_mic = example_dir / "Au_txt_Reconstructed.mic"
    test_mic = work_dir / "Au_txt_Reconstructed.mic"

    if ref_mic.exists() and test_mic.exists():
        passed = compare_reconstructions(ref_mic, test_mic)
    elif not ref_mic.exists():
        print(f"\nSkipping comparison: reference mic not found at {ref_mic}")
        passed = None
    else:
        print(f"\nError: test reconstruction not found at {test_mic}")
        passed = False

    print(f"\n{'='*60}")
    print(f"  NF-HEDM Benchmark Test Completed")
    print(f"{'='*60}")
    print(f"\nReconstruction output is in: {work_dir}")
    print(f"To clean up: rm -rf {work_dir}")

    if passed is False:
        sys.exit(1)


if __name__ == "__main__":
    main()
