#!/usr/bin/env python3
"""
UnpackConsolidatedPeaks.py
Reads the consolidated AllPeaks_PS.bin and AllPeaks_PX.bin files generated by the
PeaksFittingOMPZarrRefactor code and writes per-frame .csv and .bin files 
in the same format as the original PeaksFittingOMPZarrRefactor_orig.c code.
This provides backward compatibility for older downstream scripts.
"""

import argparse
import os
import struct
import numpy as np

def main():
    parser = argparse.ArgumentParser(description="Unpack consolidated PeakFitting files to per-frame files.")
    parser.add_argument('data_zarr', help="Path to the original Zarr file (e.g., dataset.zarr)")
    parser.add_argument('--ps_bin', default='Temp/AllPeaks_PS.bin', help="Path to AllPeaks_PS.bin")
    parser.add_argument('--px_bin', default='Temp/AllPeaks_PX.bin', help="Path to AllPeaks_PX.bin")
    parser.add_argument('--out-dir', default="Temp", help="Directory to save the per-frame files (defaults to Temp)")
    
    args = parser.parse_args()

    # Deduce stem from the Zarr file name
    zarr_basename = os.path.basename(args.data_zarr)
    args.stem = zarr_basename
    if args.stem.endswith('.zip'):
        args.stem = args.stem[:-4]
    if args.stem.endswith('.zarr'):
        args.stem = args.stem[:-5]
        
    print(f"Using dataset stem: '{args.stem}' inferred from {zarr_basename}")
    
    # Check if files exist
    if not os.path.isfile(args.ps_bin):
        print(f"Error: Could not find {args.ps_bin}")
        return
    if not os.path.isfile(args.px_bin):
        print(f"Error: Could not find {args.px_bin}")
        return
    
    # Read PS file
    print(f"Reading {args.ps_bin}...")
    with open(args.ps_bin, 'rb') as f_ps:
        nFrames_ps = struct.unpack('<i', f_ps.read(4))[0]
        nPeaksArr_ps = np.frombuffer(f_ps.read(4 * nFrames_ps), dtype=np.int32)
        offsets_ps = np.frombuffer(f_ps.read(8 * nFrames_ps), dtype=np.int64)
        
        ps_header_size = 4 + 4*nFrames_ps + 8*nFrames_ps
        f_ps.seek(ps_header_size)
        raw_data_ps = f_ps.read()
        
    ps_data = np.frombuffer(raw_data_ps, dtype=np.float64)
    expected_ps_size = np.sum(nPeaksArr_ps) * 29
    if len(ps_data) != expected_ps_size:
        print(f"Warning: Expected {expected_ps_size} doubles in PS file, but got {len(ps_data)}")
        # To handle partial execution, only unpack up to the available data
        
    ps_data = ps_data.reshape(-1, 29)
    
    # Read PX file
    print(f"Reading {args.px_bin}...")
    with open(args.px_bin, 'rb') as f_px:
        nFrames_px = struct.unpack('<i', f_px.read(4))[0]
        nrPixels_px = struct.unpack('<i', f_px.read(4))[0]
        
        if nFrames_ps != nFrames_px:
            print(f"Error: nFrames mismatch (PS: {nFrames_ps}, PX: {nFrames_px})")
            return
            
        nPeaksArr_px = np.frombuffer(f_px.read(4 * nFrames_px), dtype=np.int32)
        offsets_px = np.frombuffer(f_px.read(8 * nFrames_px), dtype=np.int64)
        
        px_header_size = 4 + 4 + 4*nFrames_px + 8*nFrames_px
        f_px.seek(px_header_size)
        raw_data_px = f_px.read()
        
    os.makedirs(args.out_dir, exist_ok=True)
    
    ps_idx = 0
    frames_unpacked = 0
    total_peaks_written = 0
    
    for f in range(nFrames_ps):
        nPeaks = nPeaksArr_ps[f]
        if nPeaks == 0:
            continue
            
        frameNr = f + 1
        ps_file = os.path.join(args.out_dir, f"{args.stem}_{frameNr:06d}_PS.csv")
        px_file = os.path.join(args.out_dir, f"{args.stem}_{frameNr:06d}_PX.bin")
        
        # Write PS.csv
        with open(ps_file, 'w') as f_out_ps:
            # Note: The output columns match the original `fprintf` order
            f_out_ps.write("SpotID\tIntegratedIntensity\tOmega(degrees)\tYCen(px)\tZCen(px)\tIMax\tRadius(px)\tEta(degrees)\tSigmaR\tSigmaEta\tNrPixels\tTotalNrPixelsInPeakRegion\tnPeaks\tmaxY\tmaxZ\tdiffY\tdiffZ\trawIMax\treturnCode\tretVal\tBG\tSigmaGR\tSigmaLR\tSigmaGEta\tSigmaLEta\tMU\tRawSumIntensity\tmaskTouched\tFitRMSE\n")
            
            for i in range(nPeaks):
                if ps_idx + i >= len(ps_data):
                    print(f"Warning: Reached end of PS data prematurely at frame {frameNr}")
                    break
                    
                row = ps_data[ps_idx + i]
                # Mimic C's %f (6 decimal places), double format, %.1f and %.6f formats properly
                f_out_ps.write(
                    f"{int(row[0])}\t{row[1]:f}\t{row[2]:f}\t{row[3]:f}\t"
                    f"{row[4]:f}\t{row[5]:f}\t{row[6]:f}\t{row[7]:f}\t"
                    f"{row[8]:f}\t{row[9]:f}\t{int(row[10])}\t{int(row[11])}\t"
                    f"{int(row[12])}\t{int(row[13])}\t{int(row[14])}\t{row[15]:f}\t"
                    f"{row[16]:f}\t{row[17]:f}\t{int(row[18])}\t{row[19]:f}\t"
                    f"{row[20]:f}\t{row[21]:f}\t{row[22]:f}\t{row[23]:f}\t"
                    f"{row[24]:f}\t{row[25]:f}\t{row[26]:f}\t{row[27]:.1f}\t{row[28]:.6f}\n"
                )
        ps_idx += nPeaks
        
        # Write PX.bin
        offset_start = offsets_px[f] - px_header_size
        offset_px_curr = offset_start
        
        with open(px_file, 'wb') as f_out_px:
            # write header constants
            f_out_px.write(struct.pack('<i', nrPixels_px))
            f_out_px.write(struct.pack('<i', nPeaks))
            
            # calculate the total amount of pixel data for this frame to write efficiently at once
            for _ in range(nPeaks):
                if offset_px_curr >= len(raw_data_px):
                    print(f"Warning: Reached end of PX data prematurely at frame {frameNr}")
                    break
                nPx = struct.unpack_from('<i', raw_data_px, offset_px_curr)[0]
                offset_px_curr += 4 + (nPx * 4)  # 4 bytes for nPx, 4 bytes for each pixel (int16 y, int16 z)
            
            f_out_px.write(raw_data_px[offset_start:offset_px_curr])
            
        frames_unpacked += 1
        total_peaks_written += nPeaks
        
    print(f"Successfully unpacked {frames_unpacked} frames with {total_peaks_written} peaks into {os.path.abspath(args.out_dir)}")

if __name__ == '__main__':
    main()
